# Generated by Django 4.2.3 on 2023-07-06 11:25

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=pathlib.PurePosixPath('/home/dev/projects/dashboard_tax/api_django/media')),
        ),
    ]
