from django.urls import path
from .views import (CallsPerMonthView,TopNamesView,ProtocolCountByAttendantView,
                    ProtocolCountByDepartmentView, ProtocolCountByTagView,
                    MonthlyTopTagView,AverageTimeByAttendantView,
                    MonthlyComparisonView,NamesOrderView,ProtocolStatisticsView,
                    AverageCallsPerAttendantView)
urlpatterns = [
     path('calls-per-month/', CallsPerMonthView.as_view(), 
         name='calls-per-month'),
     path('monthly-comparison/', MonthlyComparisonView.as_view(),
         name='monthly-comparison'),
     path('top-names/', TopNamesView.as_view(),
         name='top-names'),
     path('protocol-by-attendant/', ProtocolCountByAttendantView.as_view(),
         name='protocol-by-attendant'),
     path('protocol-by-department/', ProtocolCountByDepartmentView.as_view(),
         name='protocol-by-department'),
     path('protocol-by-tag/', ProtocolCountByTagView.as_view(),
         name='protocol-by-tag'),
     path('protocol-top-tag-moth/', MonthlyTopTagView.as_view(),
         name='protocol-top-tag-moth'),
     path('average-time-attendant/', AverageTimeByAttendantView.as_view(),
         name='average-time-attendant'),
     path('names-order/', NamesOrderView.as_view(),name='names-order'),
     path('average-calls-per-attendant/', AverageCallsPerAttendantView.as_view(),name='average-calls-per-attendant-view'),
     path('statistics/', ProtocolStatisticsView.as_view(),
         name='statistics'),
]