# Generated by Django 4.2.3 on 2023-07-26 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_number', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('total_attendance_time', models.DurationField()),
                ('first_waiting_time', models.DurationField(blank=True, null=True)),
                ('average_waiting_time', models.DurationField(blank=True, null=True)),
                ('call_type', models.CharField(max_length=50)),
                ('attendant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendants.attendant')),
            ],
            options={
                'db_table': 'protocols',
            },
        ),
    ]
