# Generated by Django 4.2.3 on 2023-07-13 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('number_protocol', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('start_date', models.CharField(max_length=255)),
                ('end_date', models.CharField(max_length=255)),
                ('handling_time', models.CharField(max_length=255)),
                ('tags', models.CharField(max_length=255)),
                ('waiting_time', models.CharField(max_length=255)),
                ('average_waiting_time', models.CharField(max_length=255)),
                ('protocol_type', models.CharField(max_length=255)),
                ('attendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='attendants.attendant')),
            ],
            options={
                'db_table': 'protocols',
            },
        ),
    ]
