# Generated by Django 4.2.3 on 2023-08-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='is_business_hours',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='is_from_me',
            field=models.BooleanField(null=True),
        ),
    ]
