# Generated by Django 4.2.3 on 2023-08-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0002_protocol_is_business_hours_protocol_is_from_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
