# Generated by Django 4.2.3 on 2023-08-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0003_alter_protocol_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='total_attendance_time',
            field=models.DurationField(null=True),
        ),
    ]
