# Generated by Django 4.2.3 on 2023-08-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0004_alter_protocol_total_attendance_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='type_call',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
