# Generated by Django 4.2.3 on 2023-08-03 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0005_protocol_type_call'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocol',
            name='type_call',
        ),
    ]
